### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by LevCarlo** [LANL-Seismoacoustics/pysac#2]
When installing,
```
 ~\pysac\ah_bootstrap.py", line 356, in _do_upgrade
 major, minor = (int(part) for part in dist.parsed_version[:2])  
 TypeError: 'Version' object is not subscriptable_
```

**Comment by jkmacc-LANL** [comment]
Hi.  This looks like the error is emanating from `ah_bootstrap.py`, which isn’t part of this repository.  I think it may be proper to file an issue with a different project.   If I’m mistaken, please provide more I formation.

Best,
Jon
